TrajectoryPlannerROS:
   max_vel_x: 0.3
   min_vel_x: 0.2
   
   
   min_in_place_rotational_vel: 0.8
   min_in_place_vel_theta: 0.8
   escape_vel: -0.1
   
   acc_lim_x: 2.5
   acc_lim_y: 0.0 # zero for a differential drive robot
   acc_lim_theta: 3.0


   holonomic_robot: false
   
   xy_goal_tolerance: 0.10  # 10 cm
   yaw_goal_tolerance: 0.1 # about 6 degrees
      

   heading_lookahead: 0.325
   heading_scoring: false
   heading_scoring_timestep: 0.8
   occdist_scale: 0.1
   oscillation_reset_dist: 0.05
   publish_cost_grid_pc: false
   prune_plan: true

   sim_time: 1.0
   sim_granularity: 0.025
   angular_sim_granularity: 0.025
   vx_samples: 8
   vy_samples: 0 # zero for a differential drive robot
   vtheta_samples: 20
   dwa: true
   simple_attractor: false


