obstacle_range: 3.0
raytrace_range: 3.5

max_obstacle_height: 0.6
min_obstacle_height: 0.0

robot_radius: 0.25
inflation_radius: 0.3

transform_tolerance: 1.0
map_type: costmap
cost_scaling_factor: 50.0
observation_sources: scan
scan: {sensor_frame: base_scan, data_type: LaserScan, topic: /scan, marking: true, clearing: true}
